#-------------------------------
# General Site Settings
title: Aloo Travellers
logo: # You can add own logo. For example '/images/logo.png'.
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Aloo Travellers
  bio: Welcome to our blog. 
  image: '/images/aloo_logo.jpg'
  avatar: '/images/about.jpg'

# Example of adding a new link to the section author - {name: "Github", link: "https://github.com"}
author-social:
# - {name: "Facebook", link: "https://www.facebook.com/patrick.chou.5"}
# - {name: "Linkedin", link: "https://www.linkedin.com/in/yungtang-chou/"}
- {name: "Instagram", link: "https://www.instagram.com/aloo_travellers/"}

#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
contact:
# - {icon: "ion-logo-facebook", link: "https://www.facebook.com/patrick.chou.5"}
# - {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/yungtang-chou/"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/aloo_travellers/"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: aloo-travellers # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
userID: 
accessToken: 


#-------------------------------
# Google Analytics
google-analytics: "UA-185647927-1" # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: false # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
# theme: jekyll-theme-cayman